name: "devcontainer"

on: 
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/swenstone/devcontainer:latest
