name: images

on:
  push:

jobs:
  devcontainer:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_URL: ghcr.io/${{ github.repository_owner }}/devcontainer
      TEST_IMAGE_URL: ghcr.io/${{ github.repository_owner }}/devcontainer:test-${{ github.sha }}
      BUILDCACHE_IMAGE_URL: ghcr.io/${{ github.repository_owner }}/devcontainer:buildcache-${{ github.sha }}

    permissions:
      packages: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install goss
        uses: e1himself/goss-installation-action@v1

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and load test container
        uses: docker/build-push-action@v6
        with:
          #cache-from: type=gha
          cache-from: type=registry,ref=${{ env.BUILDCACHE_IMAGE_URL }}
          context: devcontainer/
          push: true
          tags: ${{ env.TEST_IMAGE_URL }}

      - name: test container with goss
        env:
          GOSS_FILES_PATH: ./devcontainer/
        run: |
          dgoss run --rm ${{ env.TEST_IMAGE_URL }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_URL }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable={{ is_default_branch }}

      - name: build and push container
        uses: docker/build-push-action@v6
        with:
          # cache-from: type=gha
          # cache-to: type=gha
          cache-from: type=registry,ref=${{ env.BUILDCACHE_IMAGE_URL }}
          cache-to: type=registry,ref=${{ env.BUILDCACHE_IMAGE_URL }},mode=max
          context: devcontainer/
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  buildcontainer:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_URL: ghcr.io/${{ github.repository_owner }}/buildcontainer
      TEST_IMAGE_URL: ghcr.io/${{ github.repository_owner }}/buildcontainer:test-${{ github.sha }}
      BUILDCACHE_IMAGE_URL: ghcr.io/${{ github.repository_owner }}/buildcontainer:buildcache-${{ github.sha }}

    permissions:
      packages: write

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install goss
        uses: e1himself/goss-installation-action@v1

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: setup buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and load test container
        uses: docker/build-push-action@v6
        with:
          # cache-from: type=gha
          cache-from: type=registry,ref=${{ env.BUILDCACHE_IMAGE_URL }}
          context: buildcontainer/
          push: true
          tags: ${{ env.TEST_IMAGE_URL }}

      - name: test container with goss
        env:
          GOSS_FILES_PATH: ./buildcontainer/
        run: |
          dgoss run --rm ${{ env.TEST_IMAGE_URL }}

      - name: extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_URL }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable={{ is_default_branch }}

      - name: build and push container
        uses: docker/build-push-action@v6
        with:
          # cache-from: type=gha
          # cache-to: type=gha
          cache-from: type=registry,ref=${{ env.BUILDCACHE_IMAGE_URL }}
          cache-to: type=registry,ref=${{ env.BUILDCACHE_IMAGE_URL }},mode=max
          context: buildcontainer/
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
